[package]
authors = ["Tyler Holmes <tyler@holmesengineering.com>"]
edition = "2018"
readme = "README.md"
name = "pensel"
version = "0.1.0"

[dependencies]
cortex-m = "0.6"
cortex-m-rt = "0.6"
panic-halt = "0.2"
rtic-monotonic = "=0.1.0-alpha.1"

# dependencies for usb serial printing
usb-device = "0.2"
usbd-serial = "0.1"
heapless = "0.7"
ufmt = "0.1"
ufmt-utils = "0.1"

[dependencies.cortex-m-rtic]
version = "0.6.0-alpha.4"

[dependencies.feather_m0]
features = ["unproven", "rtic", "rtic-monotonic", "usb"]
git = "https://github.com/atsamd-rs/atsamd/"


[features]
default = []

# this lets you use `cargo fix`!
[[bin]]
name = "pensel"
test = false
bench = false
