[package]
name = "pensel-types"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bno055 = "0.3.3"
derive_more = {version = "0.99", features = ["from", "constructor", "deref"]}
log = "0.4"
