name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - name: Install Rust (thumbv6m)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          target: thumbv6m-none-eabi
          components: clippy
      - name: Install Rust (thumbv7em)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          target: thumbv7em-none-eabihf
          components: clippy
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Update USB Drivers
        run: |
          sudo apt-get clean && sudo apt-get update
          sudo apt-get install -y libudev-dev

      - name: Build Pensel
        run: |
          cd pensel
          cargo build --features="feather-m0" --target thumbv6m-none-eabi
          cargo build --features="feather-m4" --target thumbv7em-none-eabihf

      - name: Build notepad
        run: |
          cd notepad
          cargo build --bins
          cargo test

  clippy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust (thumbv6m)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          target: thumbv6m-none-eabi
          components: clippy
      - name: Install Rust (thumbv7em)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          target: thumbv7em-none-eabihf
          components: clippy
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Update USB Drivers
        run: |
          sudo apt-get clean && sudo apt-get update
          sudo apt-get install -y libudev-dev

      - name: notepad clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path ./notepad/Cargo.toml -- -W clippy::pedantic -W clippy::nursery
          name: Notepad Clippy

      - name: pensel M0 clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path ./pensel/Cargo.toml  --features=feather-m0 --target thumbv6m-none-eabi -- -W clippy::pedantic -W clippy::nursery
          name: Pensel M0 Clippy

      - name: pensel M4 clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path ./pensel/Cargo.toml  --features=feather-m4 --target thumbv7em-none-eabihf -- -W clippy::pedantic -W clippy::nursery
          name: Pensel M4 Clippy

      - name: pensel-types clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path ./pensel-types/Cargo.toml -- -W clippy::pedantic -W clippy::nursery
          name: Pensel-Types Clippy
